version: '3.8'

services:
  db:
    image: "alpine"
    command: sh -c "apk add --no-cache sqlite && sqlite3"
    volumes:
      - db-data:/data
    tty: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data: